openapi: 3.0.0
info:
  title: DigibionicCloudv2 API Documentation
  version: 2.0.5
  description: |
    # ChangeLog

    ## v2.0.5
    - 增加國碼列表API
    - 增加unseen_msg說明
    - 修正手機格式

    ## v2.0.4
    - 修正錯誤的登入url

    # Old ChangeLog
    <details>
    <summary>Details</summary>

    ## v2.0.3
    - 修正 FittingTableData中gain的格式

    ## v2.0.2
    - 增加 FittingTableData 欄位
      - mode

    ## v2.0.1
    - 增加 FittingDeviceInfo 欄位
      - device_max_preset
      - frequency
      - serial
    - 增加 /user/fittingtable PUT API 參數
      - software
      - version
      - is_accept
    - 增加 FittingTableInfo 欄位
      - uid
    - 修正 FittingDeviceFullInfo 欄位
      - l -> left
      - r -> right

    </details>
servers:
  - description: Production
    url: https://crmapi.digibionic.com/api
tags:
  - name: Authentication
    description: 驗證相關API
  - name: User
    description: 使用者相關API
  - name: Settings
    description: 系統設定相關API
paths:
  /auth/employee:
    post:
      tags:
        - Authentication
      summary: 員工登入
      description: 員工登入
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  maxLength: 350
                  example: abc@abc.com
                password:
                  type: string
                  example: abcpassword
      responses:
        200:
          description: 登入成功的回應
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  result:
                    type: string
                    description: JWToken
                    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOjEsImlzRW1wbG95ZWUiOnRydWUsImp0aSI6IjExMTExMTExLTExMTEtMTExMS0xMTExLTExMTExMTExMTExMSIsImlzcyI6ImRpZ2liaW9uaWMiLCJleHAiOjF9.JS3im7cnl5PBIshDpzhRPqVKOtDLDqKAMbiakZ50m0MLG3rOob11LvyfgTQ9aA86QpdS5vXMxLiwH9jh9PmPf5oUkclOtgUKHXwDb7Fp3u4LRlcO-qpVQEtale8EYJsgVwYwyrQEVyiqLA4NKXwm2WaLDhPkGRR7SSW1pWJMmRH7Y91ThIT1TUq2k1qwmB8Q-9IxUuEWoFibIDhbSktf982N5Jao41JSutIGl08bPkL4JNh43zlFINrZ_VPMcfTBzz8MnQQNE8aDU5jIcgvN02fD0txyhv5KWL4WOfPT0Dtv0a8P97cWSI1AsqfkkOeHLkDergxjzg_sm_uCFuXt4Q
                  empInfo:
                    type: object
                    description: 員工相關資訊
                    properties:
                      name:
                        type: string
                        description: 員工名稱
                        example: abc
                      photo:
                        type: string
                        description: 員工大頭貼
                        example: default_photo.png
                      language:
                        type: integer
                        description: |
                          員工使用語言  
                          1 - en-US  
                          2 - zh-TW  
                          3 - ja-JP
                        example: 1
                      gids:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              description: 群組名稱
                              type: string
                              example: 某某區店
                            gid:
                              description: 群組唯一識別ID
                              type: integer
                              example: 1
                            types:
                              description: |
                                群組類型  
                                1 - 公司  
                                2 - 分店
                              type: integer
                              example: 1
        404:
          description: 登入資訊有誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "dataNoFound"
                      description:
                        type: string
                        example: "Data not Found"
                  message:
                    type: string
                    example: Data Not Found
  /user:
    get:
      security:
        - authToken: []
      tags:
        - User
      summary: 獲取使用者資料列表
      description: 獲取使用者資料列表
      operationId: user_list
      parameters:
        - $ref: "#/components/parameters/PageIndex"
        - $ref: "#/components/parameters/PageSize"
        - name: is_enable
          in: query
          description: 過濾啟動或者不啟用的使用者
          schema:
            type: boolean
            example: true
        - $ref: "#/components/parameters/SelectedGroup"
      responses:
        200:
          description: 使用者資料列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  result:
                    type: array
                    minItems: 0
                    items:
                      $ref: "#/components/schemas/BaseUserInfo"
                  pagination:
                    $ref: "#/components/schemas/Pagination"
        404:
          $ref: "#/components/responses/NotFound"
    post:
      security:
        - authToken: []
      tags:
        - User
      summary: 建立使用者
      description: |
        建立使用者  
        Note: 如果X-TARGET-GID的id沒有在gid_list裡，只能讀不能寫
      operationId: user_create
      parameters:
        - $ref: "#/components/parameters/SelectedGroup"
      requestBody:
        required: true
        content:
          apllication/json:
            schema:
              oneOf:
                - required:
                    - username
                    - gender
                    - is_b2b
                    - address
                    - phone
                  type: object
                  properties:
                    username:
                      $ref: "#/components/schemas/Username"
                    gender:
                      $ref: "#/components/schemas/Gender"
                    is_b2b:
                      $ref: "#/components/schemas/IsB2B"
                    tid:
                      $ref: "#/components/schemas/TID"
                    default_payment:
                      $ref: "#/components/schemas/DefaultPayment"
                    birthday:
                      $ref: "#/components/schemas/BirthdayTimestamp"
                    phone:
                      $ref: "#/components/schemas/Phone"
                    phone_home:
                      $ref: "#/components/schemas/PhoneHome"
                    email:
                      $ref: "#/components/schemas/Email"
                    address:
                      $ref: "#/components/schemas/Address"
                    contactList:
                      $ref: "#/components/schemas/ContactList"
                  example:
                    username: abc
                    gender: 2
                    is_b2b: false
                    tid:
                    default_payment: 1
                    birthday: 1680245752760
                    phone: {
                      "code": "+866",
                      "phone": "123456789"
                    }
                    email: abc@abc.com
                    address: abc,abc,abc
                    contactList:
                      - n: 友人A
                        p: 1234567890
                - required:
                    - username
                    - gender
                    - is_b2b
                    - address
                    - phone_home
                  type: object
                  properties:
                    username:
                      $ref: "#/components/schemas/Username"
                    gender:
                      $ref: "#/components/schemas/Gender"
                    is_b2b:
                      $ref: "#/components/schemas/IsB2B"
                    tid:
                      $ref: "#/components/schemas/TID"
                    default_payment:
                      $ref: "#/components/schemas/DefaultPayment"
                    birthday:
                      $ref: "#/components/schemas/BirthdayTimestamp"
                    phone:
                      $ref: "#/components/schemas/Phone"
                    phone_home:
                      $ref: "#/components/schemas/PhoneHome"
                    email:
                      $ref: "#/components/schemas/Email"
                    address:
                      $ref: "#/components/schemas/Address"
                    contactList:
                      $ref: "#/components/schemas/ContactList"
                  example:
                    username: abc
                    gender: 2
                    is_b2b: false
                    tid:
                    default_payment: 1
                    birthday: 1680245752760
                    phone_home: 1234567890
                    email: abc@abc.com
                    address: abc,abc,abc
                    contactList:
                      - n: 友人A
                        p: 1234567890
      responses:
        200:
          $ref: "#/components/responses/BaseCreateSuccessResponse"
        422:
          $ref: "#/components/responses/BadRequest"
    put:
      security:
        - authToken: []
      tags:
        - User
      summary: 更新使用者
      description: |
        建立使用者  
        Note: 如果X-TARGET-GID的id沒有在gid_list裡，只能讀不能寫
      operationId: user_update
      parameters:
        - $ref: "#/components/parameters/SelectedGroup"
      requestBody:
        required: true
        content:
          apllication/json:
            schema:
              type: object
              properties:
                uid:
                  $ref: "#/components/schemas/UserUID"
                username:
                  $ref: "#/components/schemas/Username"
                gender:
                  $ref: "#/components/schemas/Gender"
                is_b2b:
                  $ref: "#/components/schemas/IsB2B"
                tid:
                  $ref: "#/components/schemas/TID"
                default_payment:
                  $ref: "#/components/schemas/DefaultPayment"
                birthday:
                  $ref: "#/components/schemas/BirthdayTimestamp"
                phone:
                  $ref: "#/components/schemas/Phone"
                phone_home:
                  $ref: "#/components/schemas/PhoneHome"
                email:
                  $ref: "#/components/schemas/Email"
                address:
                  $ref: "#/components/schemas/Address"
                contactList:
                  $ref: "#/components/schemas/ContactList"
      responses:
        200:
          $ref: "#/components/responses/BaseCreateSuccessResponse"
        422:
          $ref: "#/components/responses/BadRequest"
  /user/{userId}:
    get:
      security:
        - authToken: []
      tags:
        - User
      summary: 獲取使用者詳細資料
      description: |
        獲取使用者詳細資料  
        Note: 如果X-TARGET-GID的id沒有在gid_list裡，只能讀不能寫
      operationId: user_details
      parameters:
        - in: path
          name: userId
          required: true
          description: 使用者唯一識別ID
          schema:
            type: integer
            example: 100
      responses:
        200:
          description: 使用者資料列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  result:
                    allOf:
                      - $ref: "#/components/schemas/BaseUserInfo"
                      - type: object
                        properties:
                          hearing_loss:
                            $ref: "#/components/schemas/HearingLossInfo"
                      - type: object
                        properties:
                          fitting_device:
                            $ref: "#/components/schemas/FittingDeviceFullInfo"
                  pagination:
                    $ref: "#/components/schemas/Pagination"
        404:
          $ref: "#/components/responses/NotFound"
  /user/fittingReport/{userId}:
    get:
      security:
        - authToken: []
      tags:
        - User
      summary: 獲取使用者適配報告
      description: |
        獲取使用者適配報告  
        Note: 如果X-TARGET-GID的id沒有在gid_list裡，只能讀不能寫
      operationId: user_fitting_report
      parameters:
        - in: path
          name: userId
          required: true
          description: 使用者唯一識別ID
          schema:
            type: integer
            example: 100
      responses:
        200:
          description: 使用者資料列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  result:
                    type: string
                    example: "https://crm.digibionic.com/fittingReport?token=abcdefghijk"
        404:
          $ref: "#/components/responses/NotFound"
  /user/hearingloss:
    put:
      security:
        - authToken: []
      tags:
        - User
      summary: 更新使用者聽力圖
      description: |
        更新使用者聽力圖  
        Note: 如果X-TARGET-GID的id沒有在gid_list裡，只能讀不能寫
      operationId: user_audiogram_update
      parameters:
        - $ref: "#/components/parameters/SelectedGroup"
      requestBody:
        required: true
        content:
          apllication/json:
            schema:
              type: object
              properties:
                uid:
                  $ref: "#/components/schemas/UserUID"
                l:
                  description: "左耳聽力圖"
                  allOf:
                    - $ref: "#/components/schemas/AudiogramFullInfo"
                r:
                  description: "右耳聽力圖"
                  allOf:
                    - $ref: "#/components/schemas/AudiogramFullInfo"
      responses:
        200:
          $ref: "#/components/responses/BaseCreateSuccessResponse"
        422:
          $ref: "#/components/responses/BadRequest"
  /user/fittingdevice:
    put:
      security:
        - authToken: []
      tags:
        - User
      summary: 更新使用者適配裝置
      description: |
        更新使用者適配裝置  
        Note: 如果X-TARGET-GID的id沒有在gid_list裡，只能讀不能寫
      operationId: user_fitting_device_update
      parameters:
        - $ref: "#/components/parameters/SelectedGroup"
      requestBody:
        required: true
        content:
          apllication/json:
            schema:
              type: object
              properties:
                uid:
                  $ref: "#/components/schemas/UserUID"
                l:
                  allOf:
                    - $ref: "#/components/schemas/FittingDeviceRequestInfo"
                  nullable: true
                  description: "左耳適配裝置資訊"
                r:
                  allOf:
                    - $ref: "#/components/schemas/FittingDeviceRequestInfo"
                  nullable: true
                  description: "右耳適配裝置資訊"
      responses:
        200:
          $ref: "#/components/responses/BaseCreateSuccessResponse"
        422:
          $ref: "#/components/responses/BadRequest"
  /user/fittingtable:
    put:
      security:
        - authToken: []
      tags:
        - User
      summary: 更新使用者調配處方
      description: |
        更新使用者調配處方
        Note: 如果X-TARGET-GID的id沒有在gid_list裡，只能讀不能寫
      operationId: user_fitting_table_update
      parameters:
        - $ref: "#/components/parameters/SelectedGroup"
      requestBody:
        required: true
        content:
          apllication/json:
            schema:
              type: object
              properties:
                uid:
                  $ref: "#/components/schemas/UserUID"
                leftDatas:
                  allOf:
                    - $ref: "#/components/schemas/FittingTableUpdateInfo"
                  nullable: true
                  description: "左耳調配處方"
                  example:
                    data:
                      - gain:
                          - - 2
                            - 3
                            - 4
                          - - 2
                            - 3
                            - 4
                          - - 2
                            - 3
                            - 4
                        mpo:
                          - 100
                          - 200
                          - 300
                        mode: 0
                    preset: 0
                rightDatas:
                  allOf:
                    - $ref: "#/components/schemas/FittingTableUpdateInfo"
                  nullable: true
                  description: "右耳調配處方"
                  example:
                    data:
                      - gain:
                          - - 2
                            - 3
                            - 4
                          - - 2
                            - 3
                            - 4
                          - - 2
                            - 3
                            - 4
                        mpo:
                          - 100
                          - 200
                          - 300
                        mode: 0
                    preset: 0
                software:
                  $ref: "#/components/schemas/Software"
                version:
                  $ref: "#/components/schemas/Version"
                is_accept:
                  $ref: "#/components/schemas/AcceptStatus"
      responses:
        200:
          $ref: "#/components/responses/BaseCreateSuccessResponse"
        422:
          $ref: "#/components/responses/BadRequest"
  /settings/phoneCode:
    get:
      security:
        - authToken: []
      tags:
        - Settings
      summary: 獲取手機國碼列表
      description: 獲取手機國碼列表
      operationId: settings_phoneCode_list
      parameters:
        - $ref: "#/components/parameters/SelectedGroup"
      responses:
        200:
          description: 手機國碼列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  result:
                    type: array
                    minItems: 0
                    items:
                      $ref: "#/components/schemas/PhoneCodeInfo"
        404:
          $ref: "#/components/responses/NotFound"
components:
  securitySchemes:
    authToken:
      type: http
      description: 系統JWT Token
      scheme: bearer
      bearerFormat: JWT
  parameters:
    SelectedGroup:
      name: x-target-gid
      in: header
      description: 目前選擇的群組ID，從登入的gids裡面挑選
      schema:
        type: integer
        format: int32
        minimum: 1
        example: 1
    PageIndex:
      name: index
      in: query
      description: 目前存取到第幾頁，從0開始計算
      schema:
        type: integer
        format: int32
        minimum: 0
        example: 0
    PageSize:
      name: size
      in: query
      description: 一頁顯示多少列
      schema:
        type: integer
        format: int32
        minimum: 1
        example: 1
  schemas:
    UnixDatetime:
      type: integer
      description: unix時間
      example: 1592471833
    Pagination:
      type: object
      properties:
        total:
          type: integer
          description: 資料總數
          example: 1000
        limit:
          type: integer
          description: 一頁資料總數
          example: 10
        index:
          type: integer
          description: 第幾頁，從0開始計算
          example: 0
    BaseUserInfo:
      type: object
      description: 使用者相關資訊
      properties:
        uid:
          $ref: "#/components/schemas/UserUID"
        name:
          $ref: "#/components/schemas/Username"
        gender:
          $ref: "#/components/schemas/Gender"
        photo:
          type: string
          description: 使用者大頭貼
          nullable: true
          example: default_photo.png
        phone:
          $ref: "#/components/schemas/Phone"
        phone_home:
          $ref: "#/components/schemas/PhoneHome"
        address:
          $ref: "#/components/schemas/Address"
        birthday:
          $ref: "#/components/schemas/Birthday"
        email:
          $ref: "#/components/schemas/Email"
        contact_list:
          $ref: "#/components/schemas/ContactList"
        user_code:
          type: string
          description: 使用者客戶編號
          example: AA00000
        last_update:
          type: string
          description: 最後更新時間，ISO 8601格式，UTC時間
          example: 2023-01-01T01:00:00+0000
        last_login:
          type: string
          nullable: true
          description: 最後APP登入時間，ISO 8601格式，UTC時間
          example: 2023-01-01T01:00:00+0000
        is_b2b:
          $ref: "#/components/schemas/IsB2B"
        tid:
          $ref: "#/components/schemas/TID"
        default_payment:
          $ref: "#/components/schemas/DefaultPayment"
        is_enable:
          type: boolean
          description: 是否啟用
          example: true
        is_verified:
          type: boolean
          description: 是否完成驗證
          example: true
        eid_list:
          type: array
          minItems: 0
          description: 負責員工列表
          items:
            type: object
            properties:
              eid:
                type: integer
                description: 員工唯一識別ID
                example: 1
              name:
                type: string
                description: 員工名稱
                example: abc1
        gid_list:
          type: array
          minItems: 1
          description: 使用者所屬群組
          items:
            type: object
            properties:
              gid:
                type: integer
                description: 群組唯一識別ID
                example: 1
              name:
                type: string
                description: 群組名稱
                example: abc
              is_main:
                type: boolean
                description: 群組是否為主要負責群組
                example: true
        unseen_msg:
          type: number
          description: 使用者未讀訊息
    AudiogramFullInfo:
      type: object
      properties:
        125:
          type: integer
          nullable: true
          example: null
        250:
          type: integer
          nullable: true
          example: 5
        500:
          type: integer
          nullable: true
          example: 5
        750:
          type: integer
          nullable: true
          example: 5
        1000:
          type: integer
          nullable: true
          example: 5
        1500:
          type: integer
          nullable: true
          example: 5
        2000:
          type: integer
          nullable: true
          example: 5
        3000:
          type: integer
          nullable: true
          example: 5
        4000:
          type: integer
          nullable: true
          example: 5
        6000:
          type: integer
          nullable: true
          example: 5
        8000:
          type: integer
          nullable: true
          example: 5
        12500:
          type: integer
          nullable: true
          example: 5
        16000:
          type: integer
          nullable: true
          example: 5
    AudiogramInfo:
      type: object
      additionalProperties:
        type: integer
      example:
        125: 20
        500: 50
        1000: 90
    FittingTableData:
      type: object
      properties:
        eq:
          type: array
          items:
            type: integer
            example:
              - 3
              - 3
              - 3
        gain:
          description: "array順序為小中大聲音的gain"
          type: array
          maxItems: 3
          minItems: 3
          items:
            type: array
            items:
              type: integer
              example:
                - 2
                - 3
                - 4
        mpo:
          type: array
          items:
            type: integer
            example:
              - 100
              - 200
              - 300
        mode:
          type: integer
          example: 0
    FittingTableUpdateInfo:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/FittingTableData"
        preset:
          description: 最後一次更新第幾設定的資料
          type: integer
          example: 0
    FittingTableInfo:
      type: object
      properties:
        uid:
          type: integer
          description: 適配處方唯一識別ID
          example: 1
        date:
          $ref: "#/components/schemas/UnixDatetime"
        data:
          type: array
          items:
            $ref: "#/components/schemas/FittingTableData"
        preset:
          description: 最後一次更新第幾設定的資料
          type: integer
          example: 0
        is_accept:
          $ref: "#/components/schemas/AcceptStatus"
    FittingDeviceRequestInfo:
      type: object
      nullable: true
      properties:
        did:
          type: integer
          description: 適配裝置唯一識別ID
          example: 123
        serial:
          type: integer
          description: 適配裝置序號
          example: AABBCCDDEEFF
    FittingDeviceInfo:
      type: object
      properties:
        date:
          $ref: "#/components/schemas/UnixDatetime"
        device_id:
          type: integer
          description: 裝置唯一識別ID
          example: 2
        device_name:
          type: string
          description: 裝置名稱
          example: goodHearing T3
        device_config:
          type: string
          description: 裝置調整模組名稱
          example: "1862"
        device_max_bar:
          type: integer
          description: 裝置調杆最大數
          example: 32
        device_max_mode:
          type: integer
          description: 裝置可調整模式數量
          example: 3
        device_max_preset:
          type: integer
          description: 裝置最大可儲存設置
          example: 1
        frequency:
          type: array
          description: 裝置調整的頻率
          items:
            type: integer
            example:
              - 500
              - 1000
              - 2000
              - 4000
        serial:
          type: string
          description: 適配裝置序號
        brand_id:
          type: integer
          description: 裝置品牌唯一識別ID
          example: 1
        fitting_table:
          $ref: "#/components/schemas/FittingTableInfo"
    FittingDeviceFullInfo:
      type: object
      properties:
        d:
          $ref: "#/components/schemas/UnixDatetime"
      anyOf:
        - properties:
            left:
              $ref: "#/components/schemas/FittingDeviceInfo"
        - properties:
            right:
              $ref: "#/components/schemas/FittingDeviceInfo"
      example:
        d: 1592471833
        left:
          date: 1592471833
          device_id: 2
          device_name: goodHearing T3
          device_config: 1862
          device_max_bar: 32
          device_max_mode: 3
          device_max_preset: 1
          frequency:
            - 500
            - 1000
            - 2000
            - 4000
          serial: "abc"
          brand_id: 1
          fitting_table:
            date: 1592471833
            data:
              - gain:
                  - - 2
                    - 3
                    - 4
                  - - 2
                    - 3
                    - 4
                  - - 2
                    - 3
                    - 4
                mpo:
                  - 100
                  - 200
                  - 300
                mode: 0
            preset: 0
            is_accept: true
        right:
          date: 1592471833
          device_id: 2
          device_name: goodHearing T3
          device_config: 1862
          device_max_bar: 32
          device_max_mode: 3
          device_max_preset: 1
          frequency:
            - 500
            - 1000
            - 2000
            - 4000
          serial: "efg"
          brand_id: 1
          fitting_table:
            date: 1592471833
            data:
              - gain:
                  - - 2
                    - 3
                    - 4
                  - - 2
                    - 3
                    - 4
                  - - 2
                    - 3
                    - 4
                mpo:
                  - 100
                  - 200
                  - 300
                mode: 0
            preset: 0
            is_accept: true
    HearingLossInfo:
      type: object
      properties:
        d:
          $ref: "#/components/schemas/UnixDatetime"
      anyOf:
        - properties:
            l:
              $ref: "#/components/schemas/AudiogramInfo"
        - properties:
            r:
              $ref: "#/components/schemas/AudiogramInfo"
      example:
        d: 1592471833
        l:
          125: 20
          500: 50
          1000: 90
        r:
          125: 20
          500: 50
          1000: 90
    Username:
      type: string
      description: 使用者名稱
      example: abc
    Gender:
      type: integer
      description: |
        性別  
        0 - 男  
        1 - 女  
        2 - 其他
      example: 2
    Phone:
      type: object
      description: 使用者手機號碼
      nullable: true
      properties:
        code:
          description: 國碼
          type: string
          example: "+886"
        value:
          description: 手機號碼
          type: string
          pattern: ^\+?\d{10,14}
          example: 1234567890
    PhoneHome:
      type: string
      description: 使用者家用電話號碼
      nullable: true
      example: "1234567890"
    Address:
      type: string
      description: 聯絡地址
      example: abc,abc,abc
    Birthday:
      type: string
      nullable: true
      description: 生日，ISO 8601格式，UTC時間
      example: 1990-01-01T16:00:00+0000
    BirthdayTimestamp:
      type: integer
      nullable: true
      description: 生日，unix但是以milliseconds表示
      example: 1680245752760
    Email:
      type: string
      nullable: true
      description: email
      example: abc@abc.com
    ContactList:
      type: array
      minItems: 0
      maxItems: 3
      items:
        type: object
        properties:
          n:
            description: 聯絡人名稱
            type: string
            example: 友人A
          p:
            description: 聯絡人電話
            type: string
            example: 1234567890
    IsB2B:
      type: boolean
      description: 是否為B2B的客戶
      example: false
    TID:
      type: string
      nullable: true
      description: 統一編號
      example: null
    DefaultPayment:
      type: integer
      nullable: true
      description: 默認付款方式
      example: 1
    UserUID:
      type: integer
      description: 使用者唯一識別ID
      example: 1
    Software:
      type: string
      description: 軟體名稱
      example: CRM
    Version:
      type: string
      description: 版本
      example: 1.0.0
    AcceptStatus:
      type: boolean
      description: |
        是否已經接受設定  
        null - 還未接受  
        true - 已接受  
        false - 已拒絕
      nullable: true
      example: true
    PhoneCodeInfo:
      type: object
      description: 國碼資訊
      properties:
        uid:
          type: string
          description: 國碼
          example: "+886"
        isDefault:
          type: boolean
          description: 是否是公司/分店默認國碼
          example: true
  responses:
    "BaseSuccessResponse":
      description: 成功回應基本結構
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: success
              result:
                type: string
                example: success
    "BaseCreateSuccessResponse":
      description: 成功建立回應
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: success
    "NotFound":
      description: 資料不存在
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  title:
                    type: string
                    example: dataNoFound
                  description:
                    type: string
                    example: Data not Found
              message:
                type: string
                example: Data Not Found
    "BadRequest":
      description: 要求參數錯誤
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  title:
                    type: string
                    example: "wrongCode"
                  description:
                    type: string
                    example: Request got missing args or wrong data
              message:
                type: string
                example: Request got missing args or wrong data
